#  add circleci config that will build apk on oush to branch master

version: 2.1
orbs:
  flutter: circleci/flutter@1.0.0
  ruby: circleci/ruby@1.2.0

jobs:
  build-android:
    machine:
      image: android:202102-01
    resource_class: xlarge
    steps:
      - checkout
      - flutter/install_sdk:
          version: "2.5.0"

      - run:
          name: Build and Publish Android beta
          command: |
            cd android
            flutter doctor
            flutter build apk 
            echo "Apk Built"

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-android: # run on every commit
          filters:
            branches:
              only:
                - develop

